<a href="https://colab.research.google.com/github/TankEngine1234/CPTS440/blob/main/Copy_of_CPTS_440_540_Homework_2_(Spring_2024).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**HOMEWORK 2**

Assigned: February 10 (4:00PM)

Due: February 26 (11:59PM midnight)

This assignment consists **FIVE** questions. Two of them require you to generate some Python code.

--

You are expected to:

(1) clone the notebook to your own Google Drive;

(2) enter your answer and code to the cloned notebook directly; and

(3) upload the shareable link of your notebook to Canvas (as your homework submission).

**Note that if you forget to enable sharing on your Colab link, we will not be able to grade your work. You must also make sure that the sharing is for Editor rather than Viewer. Otherwise, we will not be able to run your code.**

--

**Please do NOT attempt to enter your answer directly on the original homework notebook, which is only viewable. Late submission is only possible within one day, and a deduction of 5% per day will be applied.**

**PROBLEM 1** [10pts]

Determine using the truth-table approach whether the following sentence is valid, satisfiable or unsatisfiable:

A. Is $(P \land Q) \lor \neg Q$ valid, satisfiable or unsatisfiable? Explain. [5pts]

B. Is $((P \land Q) \Rightarrow R) \iff ((P \Rightarrow R) \lor (Q \Rightarrow R))$ valid, satisfiable or unsatisfiable? Explain. [5pts]

**SOLUTION**

Truth Table Analysis:
We evaluate the formula by considering all possible truth values for P and Q: (shown in the code table below)


Explanation:

•	When Q is false, ¬Q is true regardless of P, making the entire formula true.

•	When Q is true, the truth value of the formula depends on P. In the case P=F and Q=T, both P ∧ Q ¬Q and are false, so the overall formula is false.

Since the formula is false in one case (when P=F and Q=T), it is not valid (i.e., not a tautology). However, it is satisfiable because there are several assignments (three out of four) that make the **formula true**.

*Part B:*
Analysis by Equivalences:
1.	Left-hand side:
(P∧Q)⇒R
This implication is equivalent to:
¬(P∧Q)∨Rwhich simplifies to¬P∨¬Q∨R.
2.	Right-hand side:
(P⇒R)∨(Q⇒R)
Rewrite each implication:
o	P⇒R≡¬P∨R
o	Q⇒R≡¬Q∨R
Then their disjunction becomes:
(¬P∨R)∨(¬Q∨R).
Using associativity and commutativity of ∨∨, this simplifies to:
¬P∨¬Q∨R.

Since both sides simplify to the same formula ¬P∨¬Q∨R, the biconditional
((P∧Q)⇒R)  ⟺  ((P⇒R)∨(Q⇒R))
is always true for any truth values of P, Q, and R.
Conclusion: **The formula is valid (a tautology).**


In [ ]:
import pandas as pd
from IPython.display import display

# Create the data as a dictionary
data = {
    "P": ["T", "T", "F", "F"],
    "Q": ["T", "F", "T", "F"],
    "P ∧ Q": ["T", "F", "F", "F"],
    "¬Q": ["F", "T", "F", "T"],
    "(P ∧ Q) ∨ ¬Q": ["T", "T", "F", "T"]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
display(df)


P  Q P ∧ Q ¬Q (P ∧ Q) ∨ ¬Q
0  T  T     T  F            T
1  T  F     F  T            T
2  F  T     F  F            F
3  F  F     F  T            T

**PROBLEM 2** [10pts]

Consider the following statement:

**On either Saturday or Sunday, if I am free, I will go to the concert**

Using propositional logic, we can represent it as:

$$(\mathrm{saturday} \lor \mathrm{sunday})\Rightarrow(\mathrm{free}\Rightarrow\mathrm{concert})$$

A. Convert the above sentence into its conjunctive normal form (CNF). You can use the logical equivalence table in slide 47 of Lecture 9 for this. The definition of CNF is given in slide 54 of Lecture 9. [5pts]

B. Convert the above into a conjunction of implication form of the Horn clause. Note that when a Horn clause is a disjunction of literals with exactly one positive literal, it has an implication form (slides 61 and 62 of Lecture 9). [5pts]


**SOLUTION**

Part A. Conjunctive Normal Form (CNF)
1.	Rewrite Implications:
Recall that an implication p⇒q is equivalent to ¬p∨q. So, we have:
(saturday∨sunday)⇒(free⇒concert)≡¬(saturday∨sunday)∨(¬free∨concert)
2.	Apply De Morgan’s Law:
Use De Morgan’s law on ¬(saturday∨sunday):
¬(saturday∨sunday)≡(¬saturday∧¬sunday)
So, the expression becomes:
(¬saturday∧¬sunday)∨(¬free∨concert)
3.	Distribute the Disjunction over the Conjunction:
Use the distributive property:
(A∧B)∨C≡(A∨C)∧(B∨C)
where
A=¬saturday, B=¬sunday, and C=(¬free∨concert).
This gives:
(¬saturday∨(¬free∨concert))∧(¬sunday∨(¬free∨concert))
4.	Simplify the Clauses:
Since ∨ is associative and commutative, we can write each clause as:
(¬saturday∨¬free∨concert)∧(¬sunday∨¬free∨concert)

So, the CNF is:
(¬saturday∨¬free∨concert)∧(¬sunday∨¬free∨concert)

Part B. Conjunction of Implication Form of the Horn Clause
A Horn clause is a clause with at most one positive (non-negated) literal. The CNF we found consists of two Horn clauses:
1.	Clause 1:
¬saturday∨¬free∨concert
This can be written in implication form as:
(saturday∧free)⇒concert
2.	Clause 2:
¬sunday∨¬free∨concert
This can be written in implication form as:
(sunday∧free)⇒concert
So, the conjunction of the implication forms of the Horn clauses is:
(saturday∧free)⇒concert ∧ (sunday∧free)⇒concert

*Final Answers: These are the required conversions.*

•	CNF Form:

(¬saturday∨¬free∨concert)∧(¬sunday∨¬free∨concert)

•	Horn Clause Form:

(saturday∧free)⇒concert ∧ (sunday∧free)⇒concert


**PROBLEM 3** [30pts]

Given the following:

**If the unicorn is mythical, then it is immortal, but if it is not mythical, then it is a mortal mammal. If the unicorn is either immortal or a mammal, then it is horned. The unicorn is magical if it is horned.**

Let Y denote the proposition that **the unicorn is mythical** and O denote the proposition that **the unicorn is immortal**. Let M denote the proposition that **the unicorn is mammal** and H denote the proposition that **the unicorn is horned**. Let G denote the statement that **the unicorn is magical**.

A. Provide a knowledge base of logic statements using Y, O, M, H and G (and possibly, their negations) as literals. [10pts]

B. Convert the above KB into its conjunctive normal form (CNF). [10pts]

C. Can we prove that the unicorn is magical using resolution? [5pts]

D. Can we prove that the unicorn is horned using resolution? [5pts]

**Your proving or disproving technique will NOT be graded if it does not use the resolution discussed in class**

**In addition, you are NOT allowed to introduce any other literals.**


**SOLUTION**

**A.** Knowledge Base (KB)
We first translate the English sentences into logical formulas using the given literals:
1.	If the unicorn is mythical, then it is immortal.

   Y → O
2.	If the unicorn is not mythical, then it is a mortal mammal.
   – “Mortal” means “not immortal” so:

   (a) ¬Y → ¬O

   (b) ¬Y → M
3.	If the unicorn is either immortal or a mammal, then it is horned.

(O ∨ M) → H
4.	The unicorn is magical if it is horned.

   H → G

Thus, the KB is:

•	(1) Y → O

•	(2a) ¬Y → ¬O

•	(2b) ¬Y → M

•	(3) (O ∨ M) → H

•	(4) H → G

**B. **
Conjunctive Normal Form (CNF)
We convert each implication A→B into its equivalent ¬A∨B. For (3), note that
(O∨M)→H becomes ¬(O∨M)∨H, and by De Morgan’s law,
¬(O∨M) is equivalent to (¬O∧¬M). To get CNF we distribute:
¬(O∨M)∨H≡(¬O∨H)∧(¬M∨H)
So, the CNF clauses are:
1.	Y→O becomes:                **Clause 1:**¬Y∨O.
2.	¬Y→¬O becomes:              **Clause 2:**Y∨¬O.
3.	¬Y→M¬becomes:               **Clause 3:**Y∨M.
4.	(O∨M)→H becomes two clauses:

   **Clause 4:** ¬O∨H

   **Clause 5:** ¬M∨H.
5.	H→G becomes:                 **Clause 6:**¬H∨G.

The full KB in CNF is:

(¬Y∨O)∧(Y∨¬O)∧(Y∨M)∧(¬O∨H)∧(¬M∨H)∧(¬H∨G).

C. Proving that the Unicorn is Magical (G) by Resolution
We want to show that G is entailed by the KB. In resolution, we assume the negation of what we wish to prove and show that it leads to a contradiction.
Assume: ¬G.
Now, add this to our set of clauses and proceed:
1.	From Clause 6: ¬H∨G and our assumption ¬G

  Resolving on G:

  We obtain: ¬H.

2.	From Clause 4: ¬O∨H ¬H

  Resolving on H:

  We obtain: ¬O.

3.	From Clause 5: ¬M∨H and ¬H

  Resolving on H:

  We obtain: ¬M.

4.	From Clause 1: ¬Y∨O ¬O

  Resolving on O:

  We obtain: ¬Y.

5.	From Clause 3: Y∨M and ¬M

  Resolving on M:

  We obtain: Y.

Now we have both Y and ¬Y which is a contradiction.

**Conclusion:** The assumption ¬G leads to a contradiction. Therefore, by resolution, the KB proves that the unicorn is magical.

D. Proving that the Unicorn is Horned (H) by Resolution
Next, we show that H is entailed by the KB.
Assume: ¬H.
Add this assumption to our set of clauses:
1.	From Clause 4: ¬O∨H and ¬H

  Resolving on H:

  We obtain: ¬O.
2.	From Clause 5: ¬M∨H and ¬H

  Resolving on H:

  We obtain: ¬M.
3.	From Clause 1: ¬Y∨O ¬O

  Resolving on O:

  We obtain: ¬Y.
4.	From Clause 3: Y∨M¬M

  Resolving on M:

  We obtain: Y.

Again, we derive both Y and ¬Y, a contradiction.

**Conclusion:** The assumption ¬H leads to a contradiction. Therefore, by resolution, the KB proves that the unicorn is horned.

Summary Answers

•	A. Knowledge Base:

  1. Y→O

  2. ¬Y→¬O

  3. ¬Y→M

  4. (O∨M)→H

  5. H→G

•	B. CNF:

  (¬Y∨O)∧(Y∨¬O)∧(Y∨M)∧(¬O∨H)∧(¬M∨H)∧(¬H∨G)

•	C. Is the unicorn magical?

  Yes. By assuming ¬G and applying resolution, we derive a contradiction. Hence, the unicorn is magical.

•	D. Is the unicorn horned?

  Yes. By assuming ¬H and applying resolution, we derive a contradiction. Hence, the unicorn is horned.





**PROBLEM 4** [30pts]

Implement the A* algorithm with the Manhattan distance heuristic to solve the $(n^2 -1)$-puzzle problem, which is described below:

The $n^2 - 1$ numbers $1, 2, \ldots, n^2 - 1$ are placed arbitrarily in a $n \times n$ table. One cell in the table is blank and we can swap the blank cell with one of the $4$ adjacent cells (top, down, left, right) whenever possible.

Find the shortest sequence of swapping to move from the given (starting) table to the solution table where the numbers are lined up increasingly from left to right and top to bottom with the blank cell at the bottom right.

You have already solved this problem with $n = 3$ in the previous homework.
We will now solve it with generic $n$ where $n \leq 20$.

--

The Manhattan heuristic is **the sum of Manhattan distance between each number's current position and its expected position**. Specifically, if a number is expected to be at (u, v) in the solution state but it is at (a, b) in the current state then its Manhattan distance is |a - u| + |b - v|.

For example, number 1 is expected to be at (0, 0) so if it is at (4, 5) in the current state, its Manhattan distance is |4 - 0| + |5 - 0| = 9.

--

The starting state of this problem will be given by the below procedure.

**Your code is expected to take in a starting state and return a string. Each character of the string is in in the set ['L', 'R', 'U', 'D'] which indicates swapping the blank cell with an adjacent cells in the left, right, up and down direction. If there is no solution, return None.**

In [ ]:
import math
from queue import PriorityQueue
import random
import numpy as np

def available_direction(x, n):  # this function will generate a list of possible moves
    moves = ['L', 'R', 'U', 'D']
    if x % n == 0:  # the blank cell is at column 0 so it cannot be moved any further to the left
        moves.remove('L')
    if x % n == n - 1:  # the blank cell is at column n - 1 so it cannot be moved any further to the right
        moves.remove('R')
    if x // n == 0:  # the blank cell is at row 0 so it cannot be moved up
        moves.remove('U')
    if x // n == n - 1:  # the blank cell is at row n - 1 so it cannot be moved down
        moves.remove('D')
    return moves

def puzzle_generator(n, random_step = 50):
    puzzle = list([i for i in range(1, n * n)])
    puzzle.append(0)  # we start at the solution configuration
    for i in range(random_step):  # we simulate a number of steps -- 50 steps by default
        zero_index = puzzle.index(0)  # find the index of the blank cell
        available_moves = available_direction(zero_index, n)  # check its vailable moves
        move = random.choice(available_moves) # choose a random move
        if move == 'L':  # execute it
            puzzle[zero_index], puzzle[zero_index - 1] = puzzle[zero_index - 1], puzzle[zero_index]
        elif move == 'R':
            puzzle[zero_index], puzzle[zero_index + 1] = puzzle[zero_index + 1], puzzle[zero_index]
        elif move == 'U':
            puzzle[zero_index], puzzle[zero_index - n] = puzzle[zero_index - n], puzzle[zero_index]
        elif move == 'D':
            puzzle[zero_index], puzzle[zero_index + n] = puzzle[zero_index + n], puzzle[zero_index]
    return np.array(puzzle).reshape(n, n)  # return the board after making random_step moves away from the solution configuration

In [ ]:
n = 8  # for an example, let's consider the 63-puzzle -- 63 = 8^2 - 1
puzzle = puzzle_generator(n)  # generate state
print(puzzle)  # print it out

[[ 1  2  3  4 13  5  7  8]
 [ 9 10 11 20 12  6 15  0]
 [17 18 19 28 21 23 14 16]
 [25 26 27 29 30 22 31 24]
 [33 34 35 36 37 38 39 32]
 [41 42 43 44 45 46 47 40]
 [49 50 51 52 53 54 55 48]
 [57 58 59 60 61 62 63 56]]


You can use the following code template as a starting point.

**Note that: if the length of the plan that your code returns is greater than the no. of simulation step, it is not optimal.**



In [ ]:
def heuristic(state, solution, n):  # Manhattan heuristic -- Feel free to come up with your own heuristic (bearing in mind that if the heuristic is not admissible, A* will not always find the optimal plan)
    res = 0
    # FILL IN THE REST OF THE CODE HERE TO COMPUTE THIS HEURISTIC
    return res  # return the total Manhanttan distance over all number

def direction(parent_state, child_state, n): # find the direction (i.e., U, D, L, or R) in which we can move from the parent to its immediate child
    res = ''
    # FILL IN THE CODE TO FIND RES -- IT MUST BE IN ['U', 'D', 'L', 'R']
    return res

def trace(state, parent, n):
    res = ''
    while parent[state] != None:  # if we are still at an intermediate state
        res = direction(parent[state], state, n) + res  # find the direction that moves parent[state] to state and add it to the plan
        state = parent[state]  # trace back to the parent
    return res  # return the plan

def generate(state, g, solution, n):
    res = []  # the list of children nodes

    zero_index = state.index(0)
    available_moves = available_direction(zero_index, n)  # find the list of possible move in the current state

    for move in available_moves: # for each move, we move to a different next state
        # FILL IN THE REST OF THE CODE FOR THIS FOR LOOP TO GENERATE ALL CHILDREN NODES
        # MAKE SURE YOU READ THE REST OF THE TEMPLATE OF THE SEARCH FUNCTION TO UNDERSTAND THAT WE REPRESENT A NODE = (H-VALUE, G-VALUE, NEXT STATE)

    return res  # return the list of NODES

def search(puzzle, n):  # this is the main function definition which CANNOT be changed, i.e., its name and expected input/output must NOT be changed -- otherwise, the content of the function can be changed as you see fit
    frontier = PriorityQueue()  # set up the frontier as a priority queue
    explored = dict([])  # set up the explored table, which is now a dictionary mapping from a state to its current f value
    parent = dict([])  # we also set up the parent table, which is a dictionary mapping from a state Y to its parent state X according to the current best plan to reach X

    state = tuple(puzzle.reshape(1, n * n)[0].tolist())  # flatten the N x N puzzle table into a flat vector
    parent[state] = None  # the initial state has no parent

    solution = list([i for i in range(1, n * n)])  # set up the solution state
    solution.append(0)
    solution = tuple(solution)  # why do we use tuple? tuple is hashable while list is not -- so if we want to use this as key to a dictionary, it must be in tuple form

    h, g = heuristic(state, solution, n), 0  # compute the heuristic (h) and actual-cost-so-far (g) values for the initial state
    node = (h, g, state)  # create the initial node which is a triplet (heuristic estimate to solution, actual cost so far, state)
    # MAKE SURE YOU DISTINGUISH BETWEEN PROBLEM STATE & SEARCH NODE IN THE REST OF THE IMPLEMENTATION

    frontier.put((h + g, node)) # put the node on a priority queue: add its corresponding (f, node)-tuple to the priority queue so that the node is prioritized by its f = h + g

    while not frontier.empty():  # while the frontier is not empty
        (f, (h, g, state)) = frontier.get()  # unpack the value of the (f, node)-tuple with top priority -- (f, node) where node = (h, g, state)
        if state in explored:  # if it has been explored before, this node corresponds to a sub-optimal plan
            continue  # let's ignore it and move on

        explored[state] = f  # otherwise, record that state is now explored and the current best plan to reach it has value f
        if state == solution:  # if it is a solution
            return trace(state, parent, n)  # run the tracing procedure to produce the corresponding set of moves

        children = generate(state, g, solution, n)  # otherwise, generate a set of its children nodes
        for child in children: # for each child
            # FILL IN THE REST OF THE CODE HERE
            # REFER TO THE PSEUDOCODE OF A* ALGORITHM IN LECTURE 5

    return None


IndentationError: expected an indented block after 'for' statement on line 24 (<ipython-input-6-c910e6cc1db6>, line 28)

Once you have completed the above implementation, let's get it run on a few examples to test. See the code below.

**Note that the time limit for each test case is 20 seconds. Your code is considered to FAIL a test case if it does not return a correct and optimal solution within 20 seconds.**

In [ ]:
n = 20  # set the board size
puzzle = puzzle_generator(n)  # generate a test instance (with the default 50 steps of random moves)

plan = search(puzzle, n)
print(plan)  # print out the plan
print(len(plan))  # print out the length of the plan -- this should be the minimum number of steps to reach the solution if the heuristic is admissible

NameError: name 'search' is not defined

**Solution**

In [ ]:
import math
from queue import PriorityQueue
import random
import numpy as np

def available_direction(x, n):
    # Return possible moves for the blank at index x in an n x n board.
    moves = ['L', 'R', 'U', 'D']
    if x % n == 0:         # blank in first column: cannot move left
        moves.remove('L')
    if x % n == n - 1:     # blank in last column: cannot move right
        moves.remove('R')
    if x // n == 0:        # blank in top row: cannot move up
        moves.remove('U')
    if x // n == n - 1:    # blank in bottom row: cannot move down
        moves.remove('D')
    return moves

def puzzle_generator(n, random_step=50):
    # Generate a puzzle by applying random_step moves starting from the solution.
    puzzle = list(range(1, n * n))
    puzzle.append(0)  # 0 is the blank tile
    for i in range(random_step):
        zero_index = puzzle.index(0)
        available_moves = available_direction(zero_index, n)
        move = random.choice(available_moves)
        if move == 'L':
            puzzle[zero_index], puzzle[zero_index - 1] = puzzle[zero_index - 1], puzzle[zero_index]
        elif move == 'R':
            puzzle[zero_index], puzzle[zero_index + 1] = puzzle[zero_index + 1], puzzle[zero_index]
        elif move == 'U':
            puzzle[zero_index], puzzle[zero_index - n] = puzzle[zero_index - n], puzzle[zero_index]
        elif move == 'D':
            puzzle[zero_index], puzzle[zero_index + n] = puzzle[zero_index + n], puzzle[zero_index]
    return np.array(puzzle).reshape(n, n)

def heuristic(state, solution, n):
    # Manhattan heuristic: for each nonzero tile, add the Manhattan distance between its current and goal positions.
    total = 0
    for idx, tile in enumerate(state):
        if tile != 0:
            goal_idx = tile - 1  # tile 1 should be at index 0, etc.
            curr_row, curr_col = divmod(idx, n)
            goal_row, goal_col = divmod(goal_idx, n)
            total += abs(curr_row - goal_row) + abs(curr_col - goal_col)
    return total

def direction(parent_state, child_state, n):
    # Determine the move from parent_state to child_state by comparing the blank's position.
    parent_zero = parent_state.index(0)
    child_zero = child_state.index(0)
    diff = child_zero - parent_zero
    if diff == -1:
        return 'L'
    elif diff == 1:
        return 'R'
    elif diff == -n:
        return 'U'
    elif diff == n:
        return 'D'
    return ''

def trace(state, parent, n):
    # Reconstruct the sequence of moves from the initial state to the solution state.
    res = ''
    while parent[state] is not None:
        res = direction(parent[state], state, n) + res
        state = parent[state]
    return res

def generate(state, g, solution, n):
    # Generate all children nodes from the current state.
    children = []
    state_list = list(state)
    zero_index = state_list.index(0)
    moves = available_direction(zero_index, n)
    for move in moves:
        new_state = state_list.copy()
        if move == 'L':
            swap_index = zero_index - 1
        elif move == 'R':
            swap_index = zero_index + 1
        elif move == 'U':
            swap_index = zero_index - n
        elif move == 'D':
            swap_index = zero_index + n
        # Swap the blank with the adjacent tile.
        new_state[zero_index], new_state[swap_index] = new_state[swap_index], new_state[zero_index]
        new_state_tuple = tuple(new_state)
        new_g = g + 1
        h_val = heuristic(new_state_tuple, solution, n)
        children.append((h_val, new_g, new_state_tuple))
    return children

def search(puzzle, n):
    # A* search algorithm for the puzzle.
    frontier = PriorityQueue()
    explored = {}  # maps state -> best (f = g+h) value seen so far
    parent = {}    # maps state -> parent state (for tracing the moves)

    # Flatten the puzzle into a tuple for hashing.
    state = tuple(puzzle.reshape(n * n))
    parent[state] = None
    solution = tuple(list(range(1, n * n)) + [0])
    h_val = heuristic(state, solution, n)
    g_val = 0
    node = (h_val, g_val, state)
    frontier.put((h_val + g_val, node))

    while not frontier.empty():
        f, (h_val, g_val, state) = frontier.get()
        if state in explored:
            continue  # Skip if we already found a better path to this state.
        explored[state] = f
        if state == solution:
            return trace(state, parent, n)
        # Generate children nodes.
        children = generate(state, g_val, solution, n)
        for child in children:
            child_h, child_g, child_state = child
            f_child = child_h + child_g
            # If this child state is new or found with a lower cost, update and add to the frontier.
            if child_state not in explored or f_child < explored.get(child_state, float('inf')):
                parent[child_state] = state
                frontier.put((f_child, child))
    return None

# Example usage:
if __name__ == "__main__":
    n = 8  # Example: 63-puzzle (8x8 board with 63 numbered tiles)
    puzzle = puzzle_generator(n)
    print("Puzzle:")
    print(puzzle)
    plan = search(puzzle, n)
    print("Plan:", plan)
    if plan:
        print("Plan length:", len(plan))
    else:
        print("None")


Puzzle:
[[ 2  9 11  3  5  6  7  8]
 [ 1  0 10  4 12 13 14 16]
 [17 18 19 20 21 22 15 23]
 [25 26 27 28 29 30 31 24]
 [33 34 35 36 37 38 39 32]
 [41 42 43 44 45 46 47 40]
 [49 50 51 52 53 54 55 48]
 [57 58 59 60 61 62 63 56]]
Plan: ULDRRURDRRRDRDDDDD
Plan length: 18


**FINAL NOTE: USING ABOVE TEMPLATE IS OPTIONAL. YOU CAN HAVE YOUR OWN IMPLEMENTATION AS LONG AS WE CALL YOUR search(puzzle, n) FUNCTION AND GET CORRECT RESULTS.**

**PROBLEM 5** [20pts]

In this problem, we will attempt to write a Sudoku solver using a combination of backtracking (via a recursive implementation of DFS) and constraint propagation (via AC-3).

The Sudoku problem was mentioned in slide 47 of Lecture 7. In case, it is still not clear what is the problem setting, you find its detailed description here:

https://en.wikipedia.org/wiki/Sudoku

For the AC-3 algorithm, review slides 39-46 of Lecture 7. You can also read chapter 6 of the Introduction to AI (4rd edition) textbook for a more detailed description of the AC-3 algorithm.

--

Specifically, the input to your solver will be an incomplete Sudoku board. The solver must output a complete and correct Sudoku board: no duplicate in a row, a column or a 3x3 sub-square. Both input and output are represented as 2D numpy matrices as shown in the example below.

In [ ]:
input = np.asarray([[8, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 3, 6, 0, 0, 0, 0, 0],
                   [0, 7, 0, 0, 9, 0, 2, 0, 0],
                   [0, 5, 0, 0, 0, 7, 0, 0, 0],
                   [0, 0, 0, 0, 4, 5, 7, 0, 0],
                   [0, 0, 0, 1, 0, 0, 0, 3, 0],
                   [0, 0, 1, 0, 0, 0, 0, 6, 8],
                   [0, 0, 8, 5, 0, 0, 0, 1, 0],
                   [0, 9, 0, 0, 0, 0, 4, 0, 0]])

output = np.asarray([[8, 1, 2, 7, 5, 3, 6, 4, 9],
                    [9, 4, 3, 6, 8, 2, 1, 7, 5],
                    [6, 7, 5, 4, 9, 1, 2, 8, 3],
                    [1, 5, 4, 2, 3, 7, 8, 9, 6],
                    [3, 6, 9, 8, 4, 5, 7, 2, 1],
                    [2, 8, 7, 1, 6, 9, 5, 3, 4],
                    [5, 2, 1, 9, 7, 4, 3, 6, 8],
                    [4, 3, 8, 5, 2, 6, 9, 1, 7],
                    [7, 9, 6, 3, 1, 8, 4, 5, 2]])


You are provided with the following code to check validity of the output.

In [ ]:
def is_valid(output):
    # check for completeness and valid assignment
    for r in range(9):
        for c in range(9):
            if output[r, c] not in {1, 2, 3, 4, 5, 6, 7, 8, 9}:
                return False
    # check row and column constraints
    for i in range(9):
        row_set, col_set = set(output[i, :]), set(output[:, i])
        if (len(row_set) < 9) or (len(col_set) < 9):
            return False

    # check for block constraints
    for u in range(3):
        for v in range(3):
            block_set = set(output[u * 3 : u * 3 + 3, v * 3 : v * 3 + 3].reshape(1, 9)[0].tolist())
            if len(block_set) < 9:
                return False
    return True

In [ ]:
print(is_valid(output))

True


Let us now think about the generic structure of our implementation:

**A.** The atomic unit of our algorithm is a STATE of the Sudoku problem.

**B.** The backtracking (DFS) algorithm will visit the STATES systematically until it reaches a solution. So, the abstract DFS will operate on the space of STATES

**C.** For each STATE, we can run the AC-3 algorithm to 'refine' it: STATE = AC-3(STATE) so that it becomes arc-consistent -- this will help to prune out the subtree that will grow under this state

Let's start with the implementation of STATE, which stores the list of positions that have not been assigned value; and their possible values; and whether this state is satisfiable (i.e., node-consistent)

This is best encapsulated within a class. You are provided the following code template to represent a STATE of the Sudoku problem.

In [ ]:
relationship = dict([])  # build a dictionary of global relationships between positions
for r in range(9):
    for c in range(9):  # for each position
        row_positions = set([(r, i) for i in range(9)])  # get the set of all other positions in the same row
        col_positions = set([(i, c) for i in range(9)])  # get the set of all other positions in the same column
        br, bc = r // 3, c // 3  # localize to its 3x3 sub-square
        block_posititons = set([(u, v) for u in range(br * 3, br * 3 + 3) for v in range(bc * 3, bc * 3 + 3)])  # get the set of all other positions in this block
        relationship[(r, c)] = (row_positions | col_positions) | block_posititons  # take the union of the three sets to get a single set of all other positions that cannot share the same value with (r, c)
        relationship[(r, c)].discard((r, c))

class State:
    def __init__(self, input):
        self.sudoku = input
        self.positions = dict([])  # the dictionary of all positions that have not been assigned values
        self.initialize() # initialize the possible values for each empty position
        self.is_satisfiable = True  # maintain a status of whether this state can still be satified

    def possible_values(self, r, c):  # compute the set of possible values for position (r, c)

        # FILL IN THE CODE TO COMPUTE THE SET OF POSSIBLE VALUES FOR THIS POSITION

        return set(range(1, 10)) # THIS IS THE DEFAULT -- YOU SHOULD CHANGE IT ACCORDING TO THE CODE THAT YOU FILL IN ABOVE

    def initialize(self):
        for r in range(9):  # for each row
            for c in range(9):  # for each column
                if self.sudoku[r, c] == 0:  # if this position does not have a value
                    self.positions[(r, c)] = self.possible_values(r, c)  # check the set of possible values for it
                    if len(self.positions[(r, c)]) == 0:  # if this set is empty:
                        self.is_satisfiable = False  # this state is not satisfiable

    def update(self, r, c, value):  # this is called when we assign value to position (r, c)
        self.sudoku[r, c] = value  # incorporate the assignment
        del self.positions[(r, c)]  # delete this position from the set of positions that need assignment
        for (a, b) in relationship[(r, c)]:  # for each other position in a relationship with (r, c)
            if (a, b) in self.positions:  # if this position has not been assigned a value

                # FILL IN THE REST OF THE CODE TO UPDATE THE DOMAIN VALUES FOR POSITION (a, b)
                # ALSO CHECK IF AFTER THIS UPDATE, THE STATE WILL BECOME UNSATISFIABLE, I.E., THE DOMAIN BECOMES EMPTY

        return self.is_satisfiable

Next, we will implement the AC-3 algorithm. Use the template below.

In [ ]:
def AC3(state):  # checking arc consistency
    queue = [(p, q) for p in list(state.positions.keys()) for q in relationship[p] if q in state.positions]  # push all pairs of positions which are in a relationship into the queue
    while len(queue) > 0:  # while the queue is non-empty
        (p, q) = queue.pop(0)  # take out the front candidate (p, q)

        if revise(state, p, q):
            # If the domain of p becomes empty, the state is unsatisfiable.
            if len(state.positions[p]) == 0:
                state.is_satisfiable = False
                return False
            # If revised, then add all neighbors of p (except q) back into the queue.
            for r in relationship[p]:
                if r in state.positions and r != q:
                    queue.append((r, p))

    return state.is_satisfiable  # return the satisfiable status of the state

Finally, we can start with the main backtracking search. Use the template below.

In [ ]:
import copy

def solve(state):
    if len(state.positions) == 0:
        return state.sudoku

    # FILL IN THE CODE CHOOSE A POSITION p IN state.positions TO SET VALUE
    # YOU CAN EXPERIMENT WITH DIFFERENT STRATEGIES WE DISCUSSED IN CLASS: RANDOM, MOST-CONSTRAINED POSITION AND ETC.

    for value in state.positions[p]:  # for each possible value of p
        child = copy.deepcopy(state) # create a clone so that changes made recursively to the sudoku state can easily be reverted by discarding the clone

        # FILL IN THE CODE TO UPDATE child WITH THE ASSIGNMENT OF value TO POSITION p

        res = solve(child)  # recurively search from child
        if res is not None:  # if a solution is found
            return res  # return it
        # otherwise, it res is None, child is discarded (hence, backtracking) and the loop iterates to a new value candidate (new search branch)

    return None  # all branches appear unsuccessful, return None


Now, let's use it to solve the above example.

In [ ]:
def sudoku_solver(input):
    state = State(input)  # create a state with the original configuration
    if AC3(state):  # check if it is arc-consistent
        res = solve(state)  # find a solution  # backtracking to solve it
        return res
    return None

res = sudoku_solver(input)
if is_valid(res):  # check if the returned solution is correct
    print("THE SOLUTION IS CORRECT")
else:
    print("THE SOLUTION IS WRONG")

**FINAL NOTE: USING ANY OF THE ABOVE TEMPLATE IS OPTIONAL. YOU CAN PROVIDE YOUR OWN IMPLEMENTATION AS LONG AS WE CAN CALL YOUR sudoku_solver(input) FUNCTION AND GET THE CORRECT OUTPUT.**

**THE TIME LIMIT FOR EACH TEST CASE IS 10 SECONDS. YOUR CODE WILL BE CONSIDERED TO FAIL A TEST CASE IF IT DOES NOT PROVIDE A CORRECT OUTPUT WITHIN 10 SECONDS**

**Solution**


In [ ]:
import numpy as np
import copy

# Build a dictionary of global relationships between positions.
# For each cell (r, c), relationship[(r, c)] is the set of positions that share a row, column, or 3x3 block.
relationship = dict()
for r in range(9):
    for c in range(9):
        row_positions = {(r, i) for i in range(9)}
        col_positions = {(i, c) for i in range(9)}
        br, bc = r // 3, c // 3
        block_positions = {(u, v) for u in range(br * 3, br * 3 + 3)
                                   for v in range(bc * 3, bc * 3 + 3)}
        # Union the three sets and remove the cell itself.
        relationship[(r, c)] = (row_positions | col_positions | block_positions)
        relationship[(r, c)].discard((r, c))


class State:
    def __init__(self, board):
        # board is a 9x9 numpy array where 0 indicates an empty cell.
        self.sudoku = board.copy()
        self.positions = dict()  # keys: positions (r,c) that are not yet assigned; values: possible numbers
        self.is_satisfiable = True  # indicates whether this state can still lead to a complete solution
        self.initialize()

    def possible_values(self, r, c):
        # Start with all values 1-9, then remove those that are already present in the same row, col, or block.
        possible = set(range(1, 10))
        # Remove numbers from the same row:
        possible -= set(self.sudoku[r, :])
        # Remove numbers from the same column:
        possible -= set(self.sudoku[:, c])
        # Remove numbers from the same block:
        br, bc = r // 3, c // 3
        block = self.sudoku[br*3:br*3+3, bc*3:bc*3+3]
        possible -= set(block.flatten())
        # Remove 0 if present (0 indicates an empty cell)
        possible.discard(0)
        return possible

    def initialize(self):
        # For every empty cell, compute its possible values.
        for r in range(9):
            for c in range(9):
                if self.sudoku[r, c] == 0:
                    poss = self.possible_values(r, c)
                    self.positions[(r, c)] = poss
                    if len(poss) == 0:
                        self.is_satisfiable = False

    def update(self, r, c, value):
        """
        Assign a value to cell (r,c) and update the domains of all its neighbors.
        Return self.is_satisfiable after update.
        """
        # Set the assignment.
        self.sudoku[r, c] = value
        # Remove the position from the unassigned positions.
        if (r, c) in self.positions:
            del self.positions[(r, c)]
        # For each neighbor in a relationship with (r, c), remove this value from its domain.
        for (a, b) in relationship[(r, c)]:
            if (a, b) in self.positions:
                if value in self.positions[(a, b)]:
                    self.positions[(a, b)].remove(value)
                    # If any neighbor has no possible values, the state is unsatisfiable.
                    if len(self.positions[(a, b)]) == 0:
                        self.is_satisfiable = False
        return self.is_satisfiable


def AC3(state):
    """
    Enforce arc-consistency on the current state.
    Returns True if the state is still satisfiable after propagation; False otherwise.
    """
    # Initialize the queue with all arcs (p,q) where both p and q are unassigned.
    queue = [(p, q) for p in state.positions for q in relationship[p] if q in state.positions]

    while queue:
        (p, q) = queue.pop(0)
        if revise(state, p, q):
            # If the domain of p becomes empty, the state is unsatisfiable.
            if len(state.positions[p]) == 0:
                state.is_satisfiable = False
                return False
            # If revised, then add all neighbors of p (except q) back into the queue.
            for r in relationship[p]:
                if r in state.positions and r != q:
                    queue.append((r, p))
    return state.is_satisfiable

def revise(state, p, q):
    """
    Revise the domain of p using the domain of q.
    For the inequality constraint, if q's domain is a singleton,
    then p cannot take that value.
    Returns True if the domain of p was revised.
    """
    revised = False
    # Only enforce if q has a single value (i.e. it is essentially assigned by constraint propagation).
    if len(state.positions[q]) == 1:
        val = next(iter(state.positions[q]))
        if val in state.positions[p]:
            state.positions[p].remove(val)
            revised = True
    return revised


def solve(state):
    """
    Solve the sudoku using backtracking search combined with AC-3.
    Return the complete sudoku board if solved, or None if no solution is found.
    """
    # If no positions left, then assignment is complete.
    if len(state.positions) == 0:
        return state.sudoku

    # Choose a position p with the smallest domain (MRV heuristic)
    p = min(state.positions, key=lambda pos: len(state.positions[pos]))

    # Try every possible value in the domain of p.
    for value in state.positions[p].copy():
        child = copy.deepcopy(state)
        if not child.update(p[0], p[1], value):
            continue  # If assignment makes state unsatisfiable, skip.
        if not AC3(child):
            continue  # If AC-3 detects inconsistency, skip.
        res = solve(child)
        if res is not None:
            return res  # Found a valid solution.
    # No value led to a solution from this state.
    return None

def sudoku_solver(input_board):
    """
    Main function: given a numpy 2D array representing the sudoku board,
    return a completed board (also as a numpy array) if a solution exists.
    """
    state = State(input_board)
    if not AC3(state):
        return None
    return solve(state)


# Helper function to verify a solution.
def is_valid(output):
    # Check for completeness: every cell must have a value 1-9.
    for r in range(9):
        for c in range(9):
            if output[r, c] not in {1, 2, 3, 4, 5, 6, 7, 8, 9}:
                return False
    # Check row and column constraints.
    for i in range(9):
        if len(set(output[i, :])) < 9 or len(set(output[:, i])) < 9:
            return False
    # Check block constraints.
    for u in range(3):
        for v in range(3):
            block_set = set(output[u*3:u*3+3, v*3:v*3+3].flatten().tolist())
            if len(block_set) < 9:
                return False
    return True


# Example usage:
if __name__ == '__main__':
    input_board = np.asarray([[8, 0, 0, 0, 0, 0, 0, 0, 0],
                              [0, 0, 3, 6, 0, 0, 0, 0, 0],
                              [0, 7, 0, 0, 9, 0, 2, 0, 0],
                              [0, 5, 0, 0, 0, 7, 0, 0, 0],
                              [0, 0, 0, 0, 4, 5, 7, 0, 0],
                              [0, 0, 0, 1, 0, 0, 0, 3, 0],
                              [0, 0, 1, 0, 0, 0, 0, 6, 8],
                              [0, 0, 8, 5, 0, 0, 0, 1, 0],
                              [0, 9, 0, 0, 0, 0, 4, 0, 0]])

    res = sudoku_solver(input_board)
    if res is not None and is_valid(res):
        print("THE SOLUTION IS CORRECT")
        print(res)
    else:
        print("THE SOLUTION IS WRONG or no solution found")


THE SOLUTION IS CORRECT
[[8 1 2 7 5 3 6 4 9]
 [9 4 3 6 8 2 1 7 5]
 [6 7 5 4 9 1 2 8 3]
 [1 5 4 2 3 7 8 9 6]
 [3 6 9 8 4 5 7 2 1]
 [2 8 7 1 6 9 5 3 4]
 [5 2 1 9 7 4 3 6 8]
 [4 3 8 5 2 6 9 1 7]
 [7 9 6 3 1 8 4 5 2]]
